version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: python -m pytest

         
workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
